# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week6_homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week6_homework

pod 'Alamofire', '~> 5.2.2'

end
